version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: barbershop
    # volumes:
    #   - ./data:/var/lib/postgresql/data
  test-db:
    image: postgres:13
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: barbershop-test-db
